kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  - containerPort: 50051
    hostPort: 50051
    protocol: TCP
  - containerPort: 2379
    hostPort: 2379
    protocol: TCP
  - containerPort: 8444
    hostPort: 8444
    protocol: TCP
  - containerPort: 55688
    hostPort: 55688
    protocol: TCP
networking:
  # disable CNI by defaultï¼Œbecause we will use Cilium
  disableDefaultCNI: true
  # set Kind network to support LoadBalancer
  kubeProxyMode: "none"